---
title: "Interactions between Region and Style on Panel Count by Page"
author: "Drew Hendrickson"
date: "`r Sys.Date()`"
output: html_document
---

### First, read, clean, and select the data

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}

library(tidyverse)
library(lme4)
library(pander)
library(ggplot2)

```




```{r read_and_format_data}



source("paths.R")

data <- read_csv(paste0(clean_path, "page_data.csv"))

# drop Alternative comics to allow interaction terms
tmp <- data[data$StyleBroad != "Alternative",]
print(paste0("Rows in full data: ", 
             nrow(data),
             ", rows in reduced data: ",
             nrow(tmp),
             ", diff is ",
             nrow(data) - nrow(tmp)))
data <- tmp
rm(tmp)

data$DocumentID <- factor(data$Document.Directory)
data$RegionSimplified <- factor(data$RegionSimplified)
data$StyleBroad <- factor(data$StyleBroad)
data$Page <- factor(data$Page.Number)
data$Year <- factor(data$Publication.Date)

```

```{r select_vars}

data <- data %>%
  select(panel_count, 
         Year, RegionSimplified, StyleBroad,
         LangFinal_WordStructureRaw,
         LangFinal_WALS_VerbInflection,
         DocumentID, Page)

str(data)

```

# Inspect the data


### Region by Style

the Alternative style has been removed and now the interaction can be included.

```{r }

pander( table(data$RegionSimplified, data$StyleBroad) )

```




# Now, we look at model comparisons

## Interaction between style and Region

Is there an interaction between style and region when added to a model with all other factors

```{r interaction_analysis}

full_model <- lmer(panel_count ~ StyleBroad + RegionSimplified + 
                     StyleBroad : RegionSimplified + 
                     Year + LangFinal_WordStructureRaw + 
                     LangFinal_WALS_VerbInflection + (1 | DocumentID),
                   data = data)

alt_model <- lmer(panel_count ~ StyleBroad + RegionSimplified + 
                    Year + LangFinal_WordStructureRaw + 
                    LangFinal_WALS_VerbInflection + (1 | DocumentID),
                  data = data)

pander( anova(alt_model, full_model) )

```

## Plot of the interaction


```{r plot-interaction}

ggplot(data,
       aes(x = RegionSimplified, 
           y = panel_count,
           fill = StyleBroad)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Region",
       y = "Panels per Page",
       fill = "Style") +
  theme(legend.position="top",
        axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
  

```
